#!/usr/bin/env ruby
 
site 'http://community.opscode.com/api/v1'
 
cookbook 'apt'
cookbook 'build-essential'


cookbook 'git',     github: 'fnichol/chef-git'
cookbook 'nodejs',  github: 'hectcastro/chef-nodejs'
cookbook 'curl',    github: 'phlipper/chef-curl'
cookbook 'locale'
cookbook 'imagemagick'
cookbook 'xvfb',    github: 'trywildcard/chef-xvfb'
cookbook 'firefox', github: 'substantial/cookbook-firefox'

# Manage ruby installations
cookbook 'rvm', github: 'fnichol/chef-rvm'

# Database
#cookbook 'set_locale', github: 'phlipper/chef-postgres-locale'
cookbook 'postgresql', github: 'phlipper/chef-postgresql', ref: '0.5.0'


# Terminal utilities
cookbook 'oh_my_zsh', github: 'lxmx/chef-oh-my-zsh'
